INSERT INTO restaurants.restaurant (id, name, address, avgprice, distance, cuisine, img) VALUES (1, 'Longinos', 'Paseo General Martinez Campos 49, 28010 Madrid', 11.90, 1, 'Spanish', 'https://i.postimg.cc/k5FXRkMf/longinos.jpg');
INSERT INTO restaurants.restaurant (id, name, address, avgprice, distance, cuisine, img) VALUES (2, 'VIPS', 'Calle de Miguel Ángel, 11, 28006 Madrid', 10.50, 4, 'International', 'https://i.postimg.cc/pXc3LkD4/VIPSOK.jpg');
INSERT INTO restaurants.restaurant (id, name, address, avgprice, distance, cuisine, img) VALUES (3, 'Goiko Grill', 'Calle de María de Molina, 20, 28006 Madrid', 14.60, 10, 'Burger', 'https://i.postimg.cc/SKxd5Y14/goiko.jpg');
INSERT INTO restaurants.restaurant (id, name, address, avgprice, distance, cuisine, img) VALUES (4, 'New York Burger', 'Calle de Miguel Ángel, 16, 28010 Madrid', 13.20, 3, 'Burger', 'https://i.postimg.cc/fLzRNDnY/NYBurger-Moraleja.jpg');
INSERT INTO restaurants.restaurant (id, name, address, avgprice, distance, cuisine, img) VALUES (5, 'La Mucca', 'Calle de Serrano, 91, 28006 Madrid', 13.90, 8, 'International', 'https://i.postimg.cc/pV7R0DTf/grupo-la-musa-latina-madrid-4-rincon-lamparas-techo.jpg');
INSERT INTO restaurants.restaurant (id, name, address, avgprice, distance, cuisine, img) VALUES (6, 'Ramen Shifu', 'Calle de Zurbano, 67, 28010 Madrid', 11.90, 6, 'Japanese', 'https://i.postimg.cc/GpdbWMKs/Ramen-Shifu-Grupo-Ayala-Japon.jpg');
INSERT INTO restaurants.restaurant (id, name, address, avgprice, distance, cuisine, img) VALUES (7, 'Honest Greens', 'Calle de Velázquez, 123, 28006 Madrid', 11.50, 12, 'International', 'https://i.postimg.cc/MpyWrk7S/15341570540839.jpg');
INSERT INTO restaurants.restaurant (id, name, address, avgprice, distance, cuisine, img) VALUES (8, 'Jose Luis', 'Calle del Gral Oraá, 5, 28006 Madrid', 14.20, 5, 'Spanish', 'https://i.postimg.cc/13xmHRNB/l.jpg');
INSERT INTO restaurants.restaurant (id, name, address, avgprice, distance, cuisine, img) VALUES (9, 'Makkila', 'Calle de Serrano, 110, 28006 Madrid', 14.90, 9, 'International', 'https://i.postimg.cc/Y0qGtrxY/Makkila-FVI.jpg');
INSERT INTO restaurants.restaurant (id, name, address, avgprice, distance, cuisine, img) VALUES (10, 'Lateral', 'Paseo de la Castellana, 42, 28046 Madrid', 13.70, 6, 'International', 'https://i.postimg.cc/ydK3rXgf/Castellana-42.jpg');

INSERT INTO restaurants.review (restaurant_id, authorname, authorimg, date, content, rate, cuisinerate, pricerate, settingrate) VALUES (1,'Daniel','','2020-03-01 16:22:45','hello',70,80,50,60), (1,'Adriana','','2020-03-02 14:32:45','hola',40,25,55,65);
